# -*- coding: utf-8 -*-
"""Aula_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFSdp8OdqowRBg_Np24-QHIA3U9HFPHZ

Escreva um script Python que execute as seguintes etapas:

Use a lista de números: [12, 45, 67, 23, 89, 34, 22, 90, 56, 78].

Calcule a média dos números usando a biblioteca numpy.

Identifique os números que são maiores que a média.

Armazene os números maiores que a média em um DataFrame do pandas.

Salve o DataFrame em um arquivo CSV chamado "numeros_maiores_que_media.csv"
"""

import numpy as np
import pandas as pd

numeros = [12, 45, 67, 23, 89, 34, 22, 90, 56, 78]

media = np.mean(numeros)

num_maiores = [num for num in numeros if num > media]
df_maiores = pd.DataFrame(num_maiores, columns=['Acima da media'])
print(df_maiores)

df_maiores.to_csv('numeros_maiores_que_media.csv', index=False)